"""The Hydronic builder's P&ID symbols, as data for the study renderer.

GENERATED by tools/sync_symbols.py from energy-flow-x-ui/src/assets/pid. Do not edit by hand: change
the symbol in the builder, or the map in study_glyphs.py, and run the tool again.

Each entry: `box`, the ink box as an SVG viewBox; `body`, the shapes, stroked in currentColor with
non-scaling strokes in pixels; `ports`, where each connection sits and which way it faces; `source`,
the drawing the symbol was authored in.
"""

SYMBOLS = {
    'fixed-pressure': {
        "box": (21.875, 21.875, 46.875, 56.25),
        "body": '<path d="M68.75 21.875L62.632 22.116L56.618 22.833L50.812 24.016L45.313 25.643L40.214 27.687L35.604 30.113L31.562 32.879L28.155 35.938L25.443 39.237L23.472 42.721L22.276 46.329L21.875 50L22.276 53.671L23.472 57.279L25.443 60.763L28.155 64.063L31.562 67.121L35.604 69.887L40.214 72.313L45.313 74.357L50.812 75.984L56.618 77.167L62.632 77.884L68.75 78.125L68.75 21.875Z" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M34.375 53.125L62.5 53.125M48.438 53.125L48.438 40.625" stroke-width="1.4" vector-effect="non-scaling-stroke"/>',
        "ports": (('out', 68.75, 50.0, 'right'),),
        "source": 'pid-symbols.dxf',
    },
    'fixed-demand': {
        "box": (12.5, 21.875, 65.625, 56.25),
        "body": '<path fill="currentColor" stroke="none" d="M31.25 50L20.313 44.531L20.313 55.469L31.25 50Z"/><path d="M31.25 21.875L37.368 22.116L43.382 22.833L49.188 24.016L54.688 25.643L59.786 27.687L64.396 30.113L68.438 32.879L71.845 35.938L74.557 39.237L76.528 42.721L77.724 46.329L78.125 50L77.724 53.671L76.528 57.279L74.557 60.763L71.845 64.063L68.438 67.121L64.396 69.887L59.786 72.313L54.688 74.357L49.188 75.984L43.382 77.167L37.368 77.884L31.25 78.125L31.25 21.875Z" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M12.5 50L21.875 50" stroke-width="1.4" vector-effect="non-scaling-stroke"/>',
        "ports": (('in', 12.5, 50.0, 'left'),),
        "source": 'pid-symbols.dxf',
    },
    'outlet': {
        "box": (25.0, 25.0, 59.375, 46.875),
        "body": '<path d="M25 28.125L29.895 28.312L34.706 28.87L39.351 29.79L43.75 31.056L47.829 32.645L51.517 34.532L54.751 36.683L57.476 39.063L59.645 41.629L61.222 44.338L62.179 47.145L62.5 50L62.179 52.855L61.222 55.662L59.645 58.371L57.476 60.938L54.751 63.317L51.517 65.468L47.829 67.355L43.75 68.944L39.351 70.21L34.706 71.13L29.895 71.688L25 71.875L25 28.125Z" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M62.5 50L78.125 50A9.786 9.786 0 0 1 84.375 37.5L84.375 25" stroke-width="1.4" vector-effect="non-scaling-stroke"/>',
        "ports": (('in', 25.0, 50.0, 'left'),),
        "source": 'pid-symbols.dxf',
    },
    'pressure-tank': {
        "box": (15.0, 20.0, 170.0, 60.0),
        "body": '<path fill="currentColor" stroke="none" d="M72.5 29A2.5 2.5 0 0 0 67.5 29A2.5 2.5 0 0 0 72.5 29ZM102.5 29A2.5 2.5 0 0 0 97.5 29A2.5 2.5 0 0 0 102.5 29ZM132.5 29A2.5 2.5 0 0 0 127.5 29A2.5 2.5 0 0 0 132.5 29Z"/><path d="M45 80L155 80A30 30 0 0 0 155 20L45 20A30 30 0 0 0 45 80Z" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M45 38L155 38" stroke-width="0.95" vector-effect="non-scaling-stroke"/>',
        "ports": (('out', 155.0, 62.0, 'right'), ('in', 45.0, 62.0, 'left')),
        "source": 'pid-symbols.dxf',
    },
    'pump-horizontal': {
        "box": (12.5, 23.4375, 75.0, 53.125),
        "body": '<path fill="currentColor" stroke="none" d="M37.5 34.375L65.625 50L37.5 65.625L37.5 34.375Z"/><path d="M76.563 50A26.563 26.563 0 0 0 23.438 50A26.563 26.563 0 0 0 76.563 50ZM23.438 50L12.5 50M76.563 50L87.5 50" stroke-width="1.85" vector-effect="non-scaling-stroke"/>',
        "ports": (('discharge', 87.5, 50.0, 'right'), ('suction', 12.5, 50.0, 'left')),
        "source": 'pid-extra.dxf',
    },
    'compressor-screw-recovery': {
        "box": (18.75, 50.0, 162.5, 87.5),
        "body": '<path d="M43.75 50L156.25 50L156.25 137.5L43.75 137.5L43.75 50ZM112.5 87.5A28.125 28.125 0 0 0 56.25 87.5A28.125 28.125 0 0 0 112.5 87.5ZM143.75 87.5A28.125 28.125 0 0 0 87.5 87.5A28.125 28.125 0 0 0 143.75 87.5ZM18.75 87.5L43.75 87.5M156.25 87.5L181.25 87.5" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M18.75 118.75L43.75 118.75M156.25 118.75L181.25 118.75" stroke-width="1.4" vector-effect="non-scaling-stroke"/>',
        "ports": (('gas_in', 18.75, 87.5, 'left'), ('gas_out', 181.25, 87.5, 'right'), ('coolant_out', 181.25, 118.75, 'right'), ('coolant_in', 18.75, 118.75, 'left')),
        "source": 'pid-extra.dxf',
    },
    'wtr-boiler': {
        "box": (18.75, 18.75, 62.5, 53.125),
        "body": '<path d="M18.75 18.75L81.25 18.75L81.25 71.875L18.75 71.875L18.75 18.75Z" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M25 31.25L27.083 28.906L29.167 27.191L31.25 26.563L33.333 27.191L35.417 28.906L37.5 31.25L39.583 33.594L41.667 35.309L43.75 35.938L45.833 35.309L47.917 33.594L50 31.25L52.083 28.906L54.167 27.191L56.25 26.563L58.333 27.191L60.417 28.906L62.5 31.25L64.583 33.594L66.667 35.309L68.75 35.938L70.833 35.309L72.917 33.594L75 31.25" stroke-width="0.95" vector-effect="non-scaling-stroke"/><path d="M29.688 68.75L39.063 68.75L34.375 40.625L29.688 68.75ZM45.313 68.75L54.688 68.75L50 40.625L45.313 68.75ZM60.938 68.75L70.313 68.75L65.625 40.625L60.938 68.75Z" stroke-width="1.4" vector-effect="non-scaling-stroke"/>',
        "ports": (('in', 18.75, 31.25, 'left'), ('out', 81.25, 31.25, 'right')),
        "source": 'pid-symbols.dxf',
    },
    'wtr-hx-plate': {
        "box": (28.125, 18.75, 43.75, 62.5),
        "body": '<path d="M28.125 18.75L71.875 18.75L71.875 81.25L28.125 81.25L28.125 18.75Z" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M37.5 25L37.5 75M45.313 25L45.313 75M54.688 25L54.688 75M62.5 25L62.5 75" stroke-width="1.4" vector-effect="non-scaling-stroke"/>',
        "ports": (('hot_in', 28.125, 28.125, 'left'), ('cold_out', 71.875, 28.125, 'right'), ('cold_in', 71.875, 71.875, 'right'), ('hot_out', 28.125, 71.875, 'left')),
        "source": 'pid-symbols.dxf',
    },
    'storage-tank': {
        "box": (15.0, 10.0, 70.0, 180.0),
        "body": '<path d="M15 155A35 35 0 0 0 85 155L85 45A35 35 0 0 0 15 45L15 155Z" stroke-width="1.85" vector-effect="non-scaling-stroke"/><path d="M15 70L85 70" stroke-width="0.95" vector-effect="non-scaling-stroke"/>',
        "ports": (('in', 15.0, 50.0, 'left'), ('out', 15.0, 150.0, 'left')),
        "source": 'pid-symbols.dxf',
    },
}
