#!/usr/bin/env python3
"""Embed the Hydronic builder's P&ID symbols into the study renderer, as data.

Run from the repository root, with energy-flow-x-ui checked out beside this repository:

    python tools/sync_symbols.py            # rewrite skills/hydronic/scripts/study_symbols.py
    python tools/sync_symbols.py --check    # exit 1 if that file has drifted from the builder's symbols

WHY DATA AND NOT FILES. The renderer has to stay one self-contained script with no files to find at run
time, and the plugin directory holds a plugin for review when a script refers to bundled image files. So
the symbols travel as strings inside a Python module, and this is the only thing that writes that module.

WHAT IT COPIES. Exactly the symbols `study_glyphs.GLYPHS` names, read from that map rather than listed
again here, so the map stays the single source of truth.

WHAT IT CHANGES ON THE WAY. Two things, both so the symbols read right at the size a study draws them:

- Every stroke is made non-scaling and its width converted from drawing units to pixels. The builder's
  symbols use the same widths (3 for the outline, 2 for detail, 1 for fine lines) on every size rung, so
  one conversion gives all of them the same weight on the page, whatever their frame.
- The frame becomes the symbol's ink box (its `art` comment), so a small symbol and a large one fill a
  plate equally.

Nothing is redrawn. The paths are the builder's, byte for byte apart from those attributes.

Standard library only, Python 3.9.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "skills" / "hydronic" / "scripts"
TARGET = SCRIPTS / "study_symbols.py"
SOURCE = REPO.parent / "energy-flow-x-ui" / "src" / "assets" / "pid"

sys.path.insert(0, str(SCRIPTS))
from study_glyphs import symbol_names  # noqa: E402

_ART = re.compile(r"<!--\s*art\s+([-\d.]+),([-\d.]+)\s+([-\d.]+),([-\d.]+)\s*-->")
_ORIGIN = re.compile(r"<!--\s*\S+\s+from\s+([^\s,]+)")
_PORT = re.compile(r"<!--\s*port\s+(\S+)\s+at\s+([-\d.]+),([-\d.]+)\s+facing\s+(\w+)")
_ROOT = re.compile(r"<svg\b([^>]*)>")
_SHAPE = re.compile(r"<(path|circle|ellipse|line|polyline|polygon|rect)\b([^>]*?)\s*/>")
_ATTR = re.compile(r'([\w:-]+)="([^"]*)"')


def stroke_px(units: float) -> float:
    """A stroke width in drawing units as pixels on the page: 3 -> 1.85, 2 -> 1.4, 1 -> 0.95."""
    return round(0.45 * units + 0.5, 2)


def convert(svg: str, name: str) -> dict:
    art = _ART.search(svg)
    if not art:
        raise ValueError(f"{name}.svg has no art comment, so its ink box is unknown")
    x0, y0, x1, y1 = (float(v) for v in art.groups())
    root = dict(_ATTR.findall(_ROOT.search(svg).group(1)))
    default_width = float(root.get("stroke-width", "2"))
    shapes = []
    for tag, attrs in _SHAPE.findall(svg):
        pairs = _ATTR.findall(attrs)
        values = dict(pairs)
        if values.get("stroke") != "none":
            width = stroke_px(float(values.get("stroke-width", default_width)))
            pairs = [(k, v) for k, v in pairs if k != "stroke-width"]
            pairs += [("stroke-width", f"{width:g}"), ("vector-effect", "non-scaling-stroke")]
        shapes.append(f"<{tag} " + " ".join(f'{k}="{v}"' for k, v in pairs) + "/>")
    if not shapes:
        raise ValueError(f"{name}.svg has no shapes")
    origin = _ORIGIN.search(svg)
    return {
        "box": (x0, y0, round(x1 - x0, 4), round(y1 - y0, 4)),
        "body": "".join(shapes),
        "ports": tuple((p, float(x), float(y), facing) for p, x, y, facing in _PORT.findall(svg)),
        "source": origin.group(1) if origin else "",
    }


def build() -> str:
    """The module text for the symbols the glyph map names, from the builder's files."""
    lines = [
        '"""The Hydronic builder\'s P&ID symbols, as data for the study renderer.',
        "",
        "GENERATED by tools/sync_symbols.py from energy-flow-x-ui/src/assets/pid. Do not edit by hand: change",
        "the symbol in the builder, or the map in study_glyphs.py, and run the tool again.",
        "",
        "Each entry: `box`, the ink box as an SVG viewBox; `body`, the shapes, stroked in currentColor with",
        "non-scaling strokes in pixels; `ports`, where each connection sits and which way it faces; `source`,",
        'the drawing the symbol was authored in.',
        '"""',
        "",
        "SYMBOLS = {",
    ]
    for name in symbol_names():
        path = SOURCE / f"{name}.svg"
        entry = convert(path.read_text(encoding="utf-8"), name)
        lines.append(f"    {name!r}: {{")
        lines.append(f"        \"box\": {entry['box']!r},")
        lines.append(f"        \"body\": {entry['body']!r},")
        lines.append(f"        \"ports\": {entry['ports']!r},")
        lines.append(f"        \"source\": {entry['source']!r},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if not SOURCE.is_dir():
        print(f"No builder symbols at {SOURCE}. Check out energy-flow-x-ui beside this repository.", file=sys.stderr)
        return 2
    text = build()
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
    if "--check" in argv:
        if current != text:
            print(f"{TARGET.relative_to(REPO)} has drifted from the builder's symbols. Run tools/sync_symbols.py.")
            return 1
        print("symbols match the builder")
        return 0
    if current == text:
        print("symbols already match the builder")
        return 0
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(REPO)} ({len(symbol_names())} symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
